cc_binary(
    name = "time_tracer_example",
    srcs = ["time_tracer_example.cpp"],
    deps = [
        "//time_trace:time_trace",
        "//terminal_colors:terminal_colors_example",
        "//braille_dots:braille_dots",
    ],
)
